/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package countwords;

import javax.swing.JOptionPane;

/**
 *
 * @author AL_HRAMAIN
 */
public class WordFrame extends javax.swing.JFrame {

    /**
     * Creates new form WordFrame
     */
    public WordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        WordsText = new javax.swing.JTextArea();
        wordsBtn = new javax.swing.JButton();
        CharactersBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WordsText.setColumns(20);
        WordsText.setRows(5);
        jScrollPane1.setViewportView(WordsText);

        wordsBtn.setText("words");
        wordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsBtnActionPerformed(evt);
            }
        });

        CharactersBtn.setText("Characters");
        CharactersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharactersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CharactersBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordsBtn)
                    .addComponent(CharactersBtn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void wordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsBtnActionPerformed
        // TODO add your handling code here:
       
        String words []= WordsText.getText().split(" ");
       
        int counter = 0;
         for(int i = 0; i < words.length; i++) {
             for(int j = 0; j < words[i].length(); j++) counter++;
         }
        if(counter == 0) {
            JOptionPane.showMessageDialog(this, "number of words "+ 0, "num of words" ,JOptionPane.INFORMATION_MESSAGE);
            
        }else 

        JOptionPane.showMessageDialog(this, "number of words "+ words.length, "num of words" ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_wordsBtnActionPerformed

    private void CharactersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharactersBtnActionPerformed
        // TODO add your handling code here:
         String words []= WordsText.getText().split(" ");
         int counter = 0;
         for(int i = 0; i < words.length; i++) {
             for(int j = 0; j < words[i].length(); j++) counter++;
         }
        JOptionPane.showMessageDialog(this, "number of chars "+ counter, "num of chars" ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CharactersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CharactersBtn;
    private javax.swing.JTextArea WordsText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton wordsBtn;
    // End of variables declaration//GEN-END:variables
}
